apiVersion: apps/v1
kind: Deployment
metadata:
  name: hadoop-namenode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hadoop-namenode
  template:
    metadata:
      labels:
        app: hadoop-namenode
    spec:
      containers:
      - name: hadoop-namenode
        image: my-hadoop-namenode:latest
        ports:
        - containerPort: 9870
        - containerPort: 9000
        volumeMounts:
        - name: namenode-storage
          mountPath: /hadoop/dfs/name
      volumes:
      - name: namenode-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
spec:
  selector:
    app: hadoop-namenode
  ports:
  - protocol: TCP
    port: 9000
    targetPort: 9000
  - protocol: TCP
    port: 9870
    targetPort: 9870
