apiVersion: apps/v1
kind: Deployment
metadata:
  name: hbase-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hbase-master
  template:
    metadata:
      labels:
        app: hbase-master
    spec:
      containers:
      - name: hbase-master
        image: my-hbase-master:latest
        ports:
        - containerPort: 16000
        - containerPort: 16010
---
apiVersion: v1
kind: Service
metadata:
  name: hbase-master
spec:
  selector:
    app: hbase-master
  ports:
  - protocol: TCP
    port: 16000
    targetPort: 16000
  - protocol: TCP
    port: 16010
    targetPort: 16010
