apiVersion: apps/v1
kind: Deployment
metadata:
  name: phoenix-queryserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phoenix-queryserver
  template:
    metadata:
      labels:
        app: phoenix-queryserver
    spec:
      containers:
      - name: phoenix-queryserver
        image: my-phoenix:latest
        ports:
        - containerPort: 8765
---
apiVersion: v1
kind: Service
metadata:
  name: phoenix-queryserver
spec:
  selector:
    app: phoenix-queryserver
  ports:
  - protocol: TCP
    port: 8765
    targetPort: 8765
